a.out: main.cpp reader/transaction_parser.cpp processor/food_item.cpp processor/warehouse.cpp processor/inventory_item.cpp reader/transaction.cpp reader/file_data.cpp processor/processor.cpp
	g++ -std=c++0x $^

debug: main.cpp reader/transaction_parser.cpp processor/food_item.cpp processor/warehouse.cpp processor/inventory_item.cpp reader/transaction.cpp reader/file_data.cpp processor/processor.cpp
	g++ -g -std=c++0x $^
